theme: jekyll-theme-cayman
title: Thermoelectric Database Project
author:
  name: Rifky Syariati
  email: rifky@cphys.s.kanazawa-u.ac.jp
  
domain: thermoelectrics.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://thermoelectrics.github.io  # the base hostname and protocol for your site, e.g. http://example.com
